// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEgSQFI8ZP2ta04WJEvs2dGoWWo6WfifE',
    appId: '1:132399928525:web:dfadb4f1b2c8ad1a72c584',
    messagingSenderId: '132399928525',
    projectId: 'buksmartapp',
    authDomain: 'buksmartapp.firebaseapp.com',
    storageBucket: 'buksmartapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkyb4MG48bOmlMc5afghOoAr2WCpVRWw',
    appId: '1:132399928525:android:3617b9c416ac389572c584',
    messagingSenderId: '132399928525',
    projectId: 'buksmartapp',
    storageBucket: 'buksmartapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEA7Eay2DR1fXJSkt1vigwNvLKWb877Y',
    appId: '1:132399928525:ios:8b056e7e84f3c7d472c584',
    messagingSenderId: '132399928525',
    projectId: 'buksmartapp',
    storageBucket: 'buksmartapp.firebasestorage.app',
    iosBundleId: 'com.example.user',
  );

}